### ISSUE TITLE
Automation: Message malformed

### ISSUE THREAD

**Issue by EmAnzi3** [caiosweet/Home-Assistant-custom-components-DPC-Alert#25]
Ciao!
Sorry to bother you again but apparently I'm unable to setup the example automation reported on your page. When I try to save it I get the following message:

Message malformed: extra keys not allowed @ data['automation']

**Comment by caiosweet** [comment]
> Ciao!
> Sorry to bother you again but apparently I'm unable to setup the example automation reported on your page. When I try to save it I get the following message:
> 
> Message malformed: extra keys not allowed @ data['automation']


I think you should read how to create automations in [yaml mode](https://www.home-assistant.io/docs/automation/yaml/) or from [editor](https://www.home-assistant.io/docs/automation/editor/), or split the configuration into [packages](https://www.home-assistant.io/docs/configuration/packages/).

The example you find in the readme is an automation inserted in a package. But you can, as mentioned above, create the manual automations or add an ID (to make it compatible with the UI editor) and insert it in the default automation.yaml file without the automation header (because it is already present in the configuration.yaml file with !includes)


```
- id: dpc
  alias: Protezione Civile Notifications
  mode: queued
  max_exceeded: silent
  initial_state: true
  trigger:
  ... ...
```
